### ISSUE TITLE
Error when adding new report template

### ISSUE THREAD

**Issue by r3naissance** [factionsecurity/faction#55]
Hi Faction team! Testing out your offering and noticed an issue when trying to create multiple report templates. Could be something I'm doing wrong of course but thought I'd ask. See attachment.
![Monosnap community FACTION - Google Chrome 2024-04](https://github.com/factionsecurity/faction/assets/15810963/c4b30fb2-616d-4800-80fd-183b55428f1c)

**Comment by summitt** [comment]
I think the issue is you are trying to create a second template that is for the 'Hacking Team' and the 'Security Assessment' type. You have to create it for either a different team or a different type than the one you have already created. 

It's hard to tell with only what's available on screen so let me know if it's a different issue.

**Comment by r3naissance** [comment]
To clarify, you can only have 1 template name for each team & type pair? So I guess you don't really need a name in this case. Example, if I have a number of assessment types, Internal, External, Mobile App, Web App, etc. and I only have 1 team/company. Then I would just create as many assessment types as I need report templates for. The name would then be unnecessary as the type indicates/describes what the template is? Maybe it doesn't matter at all I'm just filling in my knowledge gap and couldn't find documentation on the UX side for best practices/typical configurations. Thank you for humoring me, product looks and performs great! I'll close as it's a "me" problem.
